### PR TITLE
Changed figure to fig in template match (fix issue with fig and fragments)

### PR DESCRIPTION
**Pull request by raybiss**
Hi Stefan,

I was trying to push to the doctales "origin"! :)
I guess forking on github and then cloning locally is the way to go.
Looking forward to contribute more in the future.
Thanks for the opportunity to learn about git, along the DITA-OT!

Raymond

### CODE REVIEW

**Review by stefan-jung — COMMENTED** [review]
@raybiss, I'm not sure about this pull request. This template overrides this DITA-OT template: https://github.com/dita-ot/dita-ot/blob/d79a8349de9c7c40cc73dfc96f0faa878fe197b4/src/main/plugins/org.dita.xhtml/xsl/dita2xhtml-util.xsl#L29

To me, your request looks correct. The question is, is there a bug in `dita2xhtml-util.xsl`. I'll ask the OT team.

**Comment by raybiss** [comment]
Ok. figure, not being a DITA element, would never match this template. Thank you!

**Comment by stefan-jung** [comment]
@raybiss, I've talked to Jarno. This template converts HTML5 to XHTML. So this is correct and I close this PR and I'm looking forward to your next PR. :smile:

**Comment by raybiss** [comment]
No problem! The fork was deleted. :( This change was nonetheless fixing my fig/@fragment issue
! :) See attached screen capture comparison between the two outputs.
compare_output_figure_fig
I'll send you the two html files by email.
Thank you.

**Pull request closed without merging**
